### ISSUE TITLE
feature(spa + seo): implement Events for Google Analytics

### ISSUE THREAD

**Issue by jedihacks** [openforge/OPENFORGE.IO#77] opened 2018-05-28 17:30 UTC
We need to make sure we are accurately tracking our traffic to openforge.io via our analytics.google.com account.

For anyone who takes on this task; I'll add them to our analytics account.

https://github.com/angulartics/angulartics2

**Comment by Wholloran** [comment] 2018-06-05 16:45
We (@PaulPaulDevelops @daftclaud Geoff and myself) reviewed google analytics and it looks good. We are tracking the traffic currently and it appears to be displaying the correct information. 

Our questions to you @jedihacks would be what specific functions would you want us to track using angularics2 that is not currently being tracked by google analytics on its own?
@PaulPaulDevelops and @daftclaud do not believe we can use that specific plugin but can mimic functionality with the existing Google Analytics tracker within the stenciljs application.

**Comment by jedihacks** [comment] 2018-06-14 14:47
Ok - this sounds good.  I just renamed the ticket to Implement Events for Google Analytics

Can you hook up events for our current analytics implementation?  https://developers.google.com/analytics/devguides/collection/analyticsjs/events

Such as button clicks, application sliders, etc.   Let's make sure they're well named so we can track them easily.

Let's do that and then mark this as done!

**Comment by Wholloran** [comment] 2018-07-13 20:46
@PaulPaulDevelops maybe we have a service that sends all the information to GA, then each item we want to track we just pass the parameters to this function. I believe we are currently listening for button clicks, so we can listen for others things as well. Check with Geoff and Jedi on what they want track specifically if not everything.

**Comment by GroveDev** [comment] 2018-07-18 06:22
This is in branch 'feature/google-events'. We need to specify which events we want to track and with what parameters we send them (category, action, label, value).

**Comment by Wholloran** [comment] 2018-07-24 15:54
The issue is backlogged, I updated ticket conversation to Teamwork Task, Closing the defect till we revisit.

**Closed by Wholloran** 2018-07-24 15:54 UTC
Labels: backlog
